name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install --yes wget unzip
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          
          # حمّل أدوات سطر الأوامر 
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip
          
          # أنشئ مجلد "latest" وحرّك cmdline-tools داخله
          mkdir -p latest
          mv cmdline-tools/* latest/
          
          # أضف المتغيرات للبيئة
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Load env
        shell: bash
        run: source $GITHUB_ENV

      # افحص هل الملف sdkmanager موجود؟
      - name: Debug check
        run: ls -R $HOME/android-sdk/cmdline-tools/latest

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install build tools and platforms
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
